language: generic
sudo: required
services:
  - docker


before_install:
  - docker build -t tylerstandish/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tylerstandish/docker-react npm run test -- --coverage
